#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY ["mentodo.api.csproj", ""]
RUN dotnet restore "./mentodo.api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "mentodo.api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "mentodo.api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mentodo.Api.dll"]